spring.application.name=UniRewards

# URL com SSL Obrigatório e KeepAlive para redes instáveis
spring.datasource.url=jdbc:postgresql://db.logixvrbnxyuklwwouad.supabase.co:5432/postgres?sslmode=require&tcpKeepAlive=true

# Credenciais (A variável DB_PASSWORD deve estar idêntica no Render)
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Hibernate - Forçando dialeto para evitar consultas extras de metadados
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Hikari - Aumentando a paciência do pool antes de dar erro
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=45000
spring.datasource.hikari.maximum-pool-size=5