spring.application.name=UniRewards

# URL de Conexão
spring.datasource.url=jdbc:postgresql://db.logixvrbnxyuklwwouad.supabase.co:5432/postgres

# Usuário e Senha
spring.datasource.username=postgres
spring.datasource.password=sZ6fiH2e2gEMdo79

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect