spring.application.name=UniRewards

# URL com SSL Obrigatório e KeepAlive para redes instáveis
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0

# Credenciais
spring.datasource.username=postgres.logixvrbnxyuklwwouad
spring.datasource.password=${DB_PASSWORD:sZ6fiH2e2gEMdo79}

# Hibernate - Configurações para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# HikariCP - Configurações para melhorar a estabilidade em redes instáveis
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.minimum-idle=1

# ===============================
# CONFIGURAÇÕES DO RABBITMQ
# ===============================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ===============================
# CONFIGURAÇÕES DE E-MAIL (Mailtrap Sandbox)
# ===============================
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=8bb7ea8f2b1806
spring.mail.password=90a1ede49a51d0
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true